apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Log pod changes with full details
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["pods"]
    verbs: ["create", "update", "patch", "delete"]
