apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend
  labels:
    app: store-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-frontend
  template:
    metadata:
      labels:
        app: store-frontend
    spec:
      containers:
      - name: store-frontend
        image: store-frontend:v1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        # Note: Frontend calls API via browser, so this env might not be used directly if logic is client-side,
        # but if using SSR/rewrites, it might be relevant. 'next.config.js' rewrites map /api to http://store-api:8080
        # which works due to K8s DNS Service discovery.
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: store-frontend
spec:
  type: LoadBalancer # Or NodePort
  selector:
    app: store-frontend
  ports:
  - port: 80
    targetPort: 3000
