apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend
  labels:
    app: store-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-frontend
  template:
    metadata:
      labels:
        app: store-frontend
    spec:
      containers:
      - name: store-frontend
        image: node:18-alpine # Placeholder
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: store-frontend
spec:
  type: LoadBalancer 
  selector:
    app: store-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
