apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: store-api-rolebinding

subjects:
- kind: ServiceAccount
  name: store-api-sa
  namespace: secure-store
roleRef:
  kind: Role
  name: store-api-role
  apiGroup: rbac.authorization.k8s.io
